<?php

/**
 * @file
 * Primary module hooks for CDP User custom register form module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_entity_type_alter().
 */
function cdp_user_custom_register_form_entity_type_alter(array &$entity_types) {
  $entity_types['user']->setFormClass('register', \Drupal\cdp_user_custom_register_form\Form\CdpUserCustomRegisterFormThatOverridesDefaultRegisterForm::class);

  $entity_types['user']->setFormClass('register_for_developers', \Drupal\user\ProfileForm::class);
  $entity_types['user']->setFormClass('register_for_team_leads', \Drupal\user\ProfileForm::class);

}
