<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function task_user_login_form_alter_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['name']['#access'] = FALSE;
  $form['mail'] = [
    '#type' => 'email',
    '#title' => t('E-mail'),
    '#description' => t("Enter your 'Taskavator' user mail."),
    '#required' => TRUE,
    '#weight' => -1,
  ];


  $form['#validate'] = array_merge(['_task_user_login_form_alter_validate_mail'], $form['#validate']);
}

function _task_user_login_form_alter_validate_mail(array &$form, FormStateInterface $form_state): void {
  $mail = $form_state->getValue('mail');
  $user = user_load_by_mail($mail);
  if ($user) {
    $form_state->setValue('name', $user->getAccountName());
  }
}

/**
 * Implements hook_form_alter().
 */
function task_user_login_form_alter_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form'){
    $form['pass']['#description'] = t("Enter your 'Taskavator' user password.");
  }
}
